docs: add zh docs for vuex 4.0
vuejs/vuex pull request #1965
Opened 2021-04-10 07:01 UTC by Alanscut

add zh docs for Vuex 4.0, most parts are based on docs of 3.0

2021-05-07 10:28 UTC, Justineo requested changes

2021-05-07 10:28 UTC, Justineo commented on docs/zh/guide/state.md
> +Vuex 通过 Vue 的插件系统将 store 实例从根组件中注入到所有的子组件里。且子组件能通过 `this.$store` 访问到。让我们更新下 `Counter` 的实现：
```suggestion
Vuex 通过 Vue 的插件系统将 store 实例从根组件中“注入”到所有的子组件里。且子组件能通过 `this.$store` 访问到。让我们更新下 `Counter` 的实现：
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/guide/testing.md
> +Mutation 很容易被测试，因为它们仅仅是一些完全依赖参数的函数。这里有一个小技巧，如果你在 `store.js` 文件中定义了 mutation，并且使用 ES2015 模块功能默认输出了 Vuex.Store 的实例，那么你仍然可以给 mutation 取个变量名然后把它输出去：
```suggestion
Mutation 很容易被测试，因为它们仅仅是一些完全依赖参数的函数。这里有一个小技巧，如果你使用了 ES2015 模块，且将 mutation 定义在了在 `store.js` 文件中，那么除了模块的默认导出外，你还应该将 mutation 进行命名导出：
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/guide/testing.md
> +如果你的 mutation 和 action 编写正确，经过合理地 mocking 处理之后这些测试应该不依赖任何浏览器 API，因此你可以直接用 webpack 打包这些测试文件然后在 Node 中执行。换种方式，你也可以用 `mocha-loader` 或 Karma + `karma-webpack`在真实浏览器环境中进行测试。
```suggestion
如果你的 mutation 和 action 编写正确，经过合理地 mocking 处理之后这些测试应该不依赖任何浏览器 API，因此你可以直接用 webpack 打包这些测试文件然后在 Node 中执行。换种方式，你也可以用 `mocha-loader` 或 Karma + `karma-webpack` 在真实浏览器环境中进行测试。
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/guide/testing.md
> +详见 [vue-loader documentation](https://vuejs.github.io/vue-loader/workflow/testing.html)。
```suggestion
详见 [Vue Loader 的文档](https://vuejs.github.io/vue-loader/workflow/testing.html)。
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/guide/typescript-support.md
> +Vuex 提供了类型声明，因此可以使用 TypeScript 定义 store，并且不需要任何特殊的 TypeScript 配置。请遵循[Vue的基本TypeScript配置](https://v3.cn.vuejs.org/guide/typescript-support.html)来配置项目。
```suggestion
Vuex 提供了类型声明，因此可以使用 TypeScript 定义 store，并且不需要任何特殊的 TypeScript 配置。请遵循 [Vue 的基本 TypeScript 配置](https://v3.cn.vuejs.org/guide/typescript-support.html)来配置项目。
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/guide/typescript-support.md
> +但是，如果你用 TypeScript 编写的 Vue 组件，则需要遵循一些步骤才能正确的为 store 提供类型声明。
```suggestion
但是，如果你使用 TypeScript 来编写 Vue 组件，则需要遵循一些步骤才能正确地为 store 提供类型声明。
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/guide/typescript-support.md
> +## Vue组件中 `$store` 属性类型声明
```suggestion
## Vue 组件中 `$store` 属性的类型声明
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/guide/typescript-support.md
> +  // 声明自己的store state
```suggestion
  // 声明自己的 store state
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/guide/typescript-support.md
> +  // 为`this.$store`提供类型声明
```suggestion
  // 为 `this.$store` 提供类型声明
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/guide/typescript-support.md
> +当使用组合式 API 编写 Vue 组件时，您可能希望 `useStore` 返回类型化的 store。为了 `useStore` 能正确返回类型化的 store， 必须执行以下步骤：
```suggestion
当使用组合式 API 编写 Vue 组件时，您可能希望 `useStore` 返回类型化的 store。为了 `useStore` 能正确返回类型化的 store，必须执行以下步骤：
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/guide/typescript-support.md
> +最后，将上述 injection key 传入 `useStore` 方法可以检索到类型化的 store。
```suggestion
最后，将上述 injection key 传入 `useStore` 方法可以获取类型化的 store。
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/index.md
> +
少了一段

> ::: tip NOTE
> This is the docs for Vuex 4, which works with Vue 3. If you're looking for docs for Vuex 3, which works with Vue 2, [please check it out here](https://vuex.vuejs.org/).
> :::

2021-05-07 10:28 UTC, Justineo commented on docs/zh/index.md
> +Vuex 是一个专为 Vue.js 应用程序开发的**状态管理模式**。它采用集中式存储管理应用的所有组件的状态，并以相应的规则保证状态以一种可预测的方式发生变化。
```suggestion
Vuex 是一个专为 Vue.js 应用程序开发的**状态管理模式 + 库**。它采用集中式存储管理应用的所有组件的状态，并以相应的规则保证状态以一种可预测的方式发生变化。
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/index.md
> +  // state
```suggestion
  // 状态
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/index.md
> +  // view
```suggestion
  // 视图
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/index.md
> +  // actions
```suggestion
  // 操作
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/index.md
> +- **actions**，响应在 **view** 上的用户输入导致的状态变化。
同上

2021-05-07 10:28 UTC, Justineo commented on docs/zh/installation.md
> +[Unpkg.com](https://unpkg.com) 提供了基于 NPM 的 CDN 链接。以上的链接会一直指向 NPM 上发布的最新版本。您也可以通过 `https://unpkg.com/vuex@4.0.0/dist/vuex.global.js` 这样的方式指定特定的版本。
```suggestion
[Unpkg.com](https://unpkg.com) 提供了基于 npm 的 CDN 链接。以上的链接会一直指向 npm 上发布的最新版本。您也可以通过 `https://unpkg.com/vuex@4.0.0/dist/vuex.global.js` 这样的方式指定特定的版本。
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/installation.md
> +### NPM
```suggestion
### npm
```

2021-05-07 10:28 UTC, Justineo commented on docs/zh/installation.md
> +[Unpkg.com](https://unpkg.com) 提供了基于 NPM 的 CDN 链接。以上的链接会一直指向 NPM 上发布的最新版本。您也可以通过 `https://unpkg.com/vuex@4.0.0/dist/vuex.global.js` 这样的方式指定特定的版本。
参考 [Vue 文档编写指南](https://v3.cn.vuejs.org/guide/contributing/writing-guide.html#:~:text=%E4%BE%8B%E5%A6%82%2C%E2%80%9Cwebpack%E2%80%9D%E5%92%8C%E2%80%9Cnpm%E2%80%9D%E9%83%BD%E5%BA%94%E4%BD%BF%E7%94%A8%E5%B0%8F%E5%86%99%E5%AD%97%E6%AF%8D%2C%E5%9B%A0%E4%B8%BA%E8%BF%99%E6%98%AF%E5%AE%83%E4%BB%AC%E7%9A%84%E6%96%87%E6%A1%A3%E5%BC%95%E7%94%A8%E5%AE%83%E4%BB%AC%E7%9A%84%E6%96%B9%E5%BC%8F%E3%80%82)。

2021-05-10 02:21 UTC, Alanscut commented on docs/.vitepress/config.js
> +              { text: 'Getters', link: '/zh/guide/getters' },
这里的复数指的是 `getters` 吗？这里是参考的vuex 3.x版本的文档，如果您觉着需要改的话，我稍后修改

2021-05-10 02:23 UTC, Alanscut commented on docs/zh/index.md
> +- **actions**，响应在 **view** 上的用户输入导致的状态变化。
`state`, `view`, `actions` 在这里是否保留为英文更容易让用户理解呢？尤其是`state`，`actions`， 在vuex中更像是专有名词

2021-05-10 03:26 UTC, Justineo commented on docs/.vitepress/config.js
> +              { text: 'Getters', link: '/zh/guide/getters' },
参见：[术语翻译约定](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E8%A2%AB%E4%BF%9D%E7%95%99%E7%9A%84%E8%8B%B1%E6%96%87%E5%8D%95%E5%A4%8D%E6%95%B0%E9%97%AE%E9%A2%98)

2021-05-10 03:28 UTC, Justineo commented on docs/zh/index.md
> +- **actions**，响应在 **view** 上的用户输入导致的状态变化。
我理解这个和专有概念并不一一对应，这里只是一个宽泛概念的描述，后面会有对专有概念详细进行介绍的。

2021-05-10 03:30 UTC, Alanscut commented
@Justineo 非常感谢您的耐心检视，按照您的意见修改后，文档更顺畅，更美观，也更规范。但是我稍微有一点疑问就是关于  `matations`、`getters` 这些专有名词是否应该翻译为中文，或者去掉复数形式：
- 关于是否保留复数形式：在原英文文档中，作为标题， `matations`、`getters` 等都是复数形式，因此是否遵循英文原文的处理方式更合适呢？
- 关于 `state`、`view`、`actions` 是否需要翻译为中文：我更偏向于将这些名词当做 Vuex 里的一些专有名词，保留英文是否更容易理解其背后的含义呢？

2021-05-10 03:33 UTC, Alanscut commented on docs/zh/index.md
> +- **actions**，响应在 **view** 上的用户输入导致的状态变化。
好的，谢谢！

2021-05-10 06:02 UTC, Justineo requested changes

2021-05-10 06:02 UTC, Justineo commented on docs/zh/guide/modules.md
> +默认情况下，模块内部的 action 和 mutation 仍然是注册在**全局命名空间**的——这样使得多个模块能够对同一个 action 或 mutation 作出响应。Getter 同样也默认注册在全局命名空间，但是目前这并非出于功能上的目的，（仅仅是维持现状来避免非兼容性变更）。必须注意，不要在不同的、无命名空间的模块中定义两个不同的 getter 从而导致错误。
```suggestion
默认情况下，模块内部的 action 和 mutation 仍然是注册在**全局命名空间**的——这样使得多个模块能够对同一个 action 或 mutation 作出响应。Getter 同样也默认注册在全局命名空间，但是目前这并非出于功能上的目的（仅仅是维持现状来避免非兼容性变更）。必须注意，不要在不同的、无命名空间的模块中定义两个不同的 getter 从而导致错误。
```

2021-05-10 06:02 UTC, Justineo commented on docs/zh/guide/typescript-support.md
> +Vuex 提供了类型声明，因此可以使用 TypeScript 定义 store，并且不需要任何特殊的 TypeScript 配置。请遵循 [Vue 的基本 TypeScript 配置](https://v3.cn.vuejs.org/guide/typescript-support.html) 来配置项目。
```suggestion
Vuex 提供了类型声明，因此可以使用 TypeScript 定义 store，并且不需要任何特殊的 TypeScript 配置。请遵循 [Vue 的基本 TypeScript 配置](https://v3.cn.vuejs.org/guide/typescript-support.html)来配置项目。
```

2021-05-10 06:24 UTC, Justineo approved these changes

2021-05-10 06:25 UTC, Justineo commented
@Alanscut Thank you very much for your hard work! I think this PR is ready to merge 👍

/cc @kiaking

2021-05-10 06:48 UTC, Alanscut commented
@Justineo Thank you for your patience and guidance, which makes the document more standardized and smooth!

2021-05-10 11:17 UTC, kiaking approved these changes
Thank you so much for the amazing work 🎉 🎉 🎉 

I've adjusted the lang list order just to match the Vuex 3 docs, and fixed link to api doc on Nav bar.

2021-05-10 11:20 UTC, merged