docs(zh): update zh docs from en docs
vuejs/vuex pull request #2150
Opened 2022-03-26 16:29 UTC by KimYangOfCat

2022-04-02 06:16 UTC, KimYangOfCat commented
@Jinjiang  hi, jinjiang, do you have any sugesttion?

2022-05-27 16:40 UTC, Jinjiang requested changes

2022-05-27 16:40 UTC, Jinjiang commented on docs/guide/mutations.md
> +    // we can use the ES2015 computed property name feature to use a constant as the function name
不建议修改英文版任何内容

2022-05-27 16:40 UTC, Jinjiang commented on docs/zh/api/index.md
> + `subscribe` 方法将返回一个 `unsubscribe` 函数，当不再需要订阅时应该调用该函数。例如，你可能会订阅一个 Vuex 模块，当你取消注册该模块时取消订阅。或者你可能从一个Vue组件内部调用 `subscribe`，然后不久就会销毁该组件。在这些情况下，你应该记得手动取消订阅。
```suggestion
 `subscribe` 方法将返回一个 `unsubscribe` 函数，当不再需要订阅时应该调用该函数。例如，你可能会订阅一个 Vuex 模块，当你取消注册该模块时取消订阅。或者你可能从一个 Vue 组件内部调用 `subscribe`，然后不久就会销毁该组件。在这些情况下，你应该记得手动取消订阅。
```

2022-05-27 16:40 UTC, Jinjiang commented on docs/zh/guide/getters.md
> +getter 会暴露为 `store.getters` 对象，你可以以属性的形式访问这些值：
应保持开头大写，这里不是特指 API 名称

2022-05-27 16:40 UTC, Jinjiang commented on docs/zh/guide/mutations.md
> +# Mutations
保持单数

2022-05-27 16:40 UTC, Jinjiang commented on docs/zh/guide/testing.md
> +如果在测试环境下有可用的 spies (比如通过 [Sinon.JS](http://sinonjs.org/))，你可以使用它们替换辅助函数 `testAction`：
保持单数

2022-05-28 07:25 UTC, KimYangOfCat commented
@Jinjiang  hi, jinjiang, thanks for your suggesttions, them has be applied.

2022-05-28 15:27 UTC, Jinjiang approved these changes

2022-05-28 15:28 UTC, merged